<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('User', 'doctrine');

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $login
 * @property string $password
 * @property string $lastname
 * @property string $firstname
 * @property boolean $locked
 * @property Doctrine_Collection $Log
 * @property Doctrine_Collection $ServerUser
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getLogin()      Returns the current record's "login" value
 * @method string              getPassword()   Returns the current record's "password" value
 * @method string              getLastname()   Returns the current record's "lastname" value
 * @method string              getFirstname()  Returns the current record's "firstname" value
 * @method boolean             getLocked()     Returns the current record's "locked" value
 * @method Doctrine_Collection getLog()        Returns the current record's "Log" collection
 * @method Doctrine_Collection getServerUser() Returns the current record's "ServerUser" collection
 * @method User                setId()         Sets the current record's "id" value
 * @method User                setLogin()      Sets the current record's "login" value
 * @method User                setPassword()   Sets the current record's "password" value
 * @method User                setLastname()   Sets the current record's "lastname" value
 * @method User                setFirstname()  Sets the current record's "firstname" value
 * @method User                setLocked()     Sets the current record's "locked" value
 * @method User                setLog()        Sets the current record's "Log" collection
 * @method User                setServerUser() Sets the current record's "ServerUser" collection
 * 
 * @package    m-vpn
 * @subpackage model
 * @author     Loïc PORTE
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('login', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('lastname', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('firstname', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('locked', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Log', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ServerUser', array(
             'local' => 'id',
             'foreign' => 'user_id'));
    }
}