<?php

/**
 * Server
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    m-vpn
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Server extends BaseServer
{
    function getConfig(){
        return "### Client configuration file for OpenVPN
client
dev tun
remote ".$this->getIp()." ".$this->getPort()."
proto ".$this->getProto()."
nobind
resolv-retry infinite
persist-key
persist-tun
ca ca.crt
cipher BF-CBC
comp-lzo
verb 3
auth-user-pass
route-method exe
route-delay 2";
    }
}

