<?php

/**
 * ServerUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServerUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServerUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServerUser');
    }
}