<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/01/11 11:59:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=mvpn',
  'username' => 'root',
  'password' => 'aliens',
  'name' => 'doctrine',
)),);
